name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies before building the project
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Build the project while passing the environment variables
      - name: Build project with environment variables
        run: |
          VITE_PUBLIC_KEY=${{ secrets.VITE_PUBLIC_KEY }} \
          VITE_SERVICE_ID=${{ secrets.VITE_SERVICE_ID }} \
          VITE_TEMPLATE_ID=${{ secrets.VITE_TEMPLATE_ID }} \
          npm run build

      # Upload production-ready build files to artifacts
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
